<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>com.flexganttfx</groupId>
		<artifactId>gantt</artifactId>
		<version>11.13.15</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	<artifactId>assembly</artifactId>
	<packaging>pom</packaging>
	<name>FlexGanttFXAssembly</name>
	<description>A module for the sole purpose of creating assemblies.</description>

	<properties>
		<maven.deploy.skip>true</maven.deploy.skip>
		<maven.javadoc.skip>true</maven.javadoc.skip>
	</properties>

	<dependencies>

		<dependency>
			<groupId>com.flexganttfx</groupId>
			<artifactId>view</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>com.flexganttfx</groupId>
			<artifactId>tutorials</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>com.flexganttfx</groupId>
			<artifactId>emirates</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>com.flexganttfx</groupId>
			<artifactId>msproject</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>com.flexganttfx</groupId>
			<artifactId>ical</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>com.flexganttfx</groupId>
			<artifactId>experimental</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>com.flexganttfx</groupId>
			<artifactId>editor</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>

			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-assembly-plugin</artifactId>
				<version>3.1.1</version>
				<configuration>
					<descriptors>
						<descriptor>${project.basedir}/src/assembly/bin.xml</descriptor>
						<descriptor>${project.basedir}/src/assembly/src.xml</descriptor>
					</descriptors>
					<finalName>flexganttfx-${project.version}</finalName>
				</configuration>
				<executions>
					<execution>
						<id>make-distribution-assembly</id> <!-- this is used for inheritance merges -->
						<phase>package</phase> <!-- bind to the packaging phase -->
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>
</project>