<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>view</artifactId>
	<name>FlexGanttFXView</name>
	<description>A com.flexganttfx.demo.gantt.Gantt chart component for JavaFX.</description>
	<packaging>bundle</packaging>
	
	<parent>
		<groupId>com.flexganttfx</groupId>
		<artifactId>gantt</artifactId>
		<version>11.12.4</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<properties>
		<maven.javadoc.skip>false</maven.javadoc.skip>
	</properties>

	<repositories>
		<repository>
			<id>oss-sonatype</id>
			<name>oss-sonatype</name>
			<url>https://oss.sonatype.org/content/repositories/snapshots/</url>
			<snapshots>
				<enabled>true</enabled>
			</snapshots>
		</repository>
	</repositories>

	<dependencies>

		<dependency>
			<groupId>com.flexganttfx</groupId>
			<artifactId>model</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>org.controlsfx</groupId>
			<artifactId>controlsfx</artifactId>
			<version>${controlsfx.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-base</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-controls</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-graphics</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-media</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-web</artifactId>
				</exclusion>
				<exclusion>
					<groupId>org.openjfx</groupId>
					<artifactId>javafx-swing</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.openjfx</groupId>
			<artifactId>javafx-controls</artifactId>
			<version>${javafx.version}</version>
		</dependency>

	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>${apache.felix.version}</version>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<Export-Package>com.flexganttfx.view.*,impl.com.flexganttfx.skin.*</Export-Package>
					</instructions>
				</configuration>
			</plugin>

			<plugin>
				<groupId>org.codehaus.mojo</groupId>
				<artifactId>exec-maven-plugin</artifactId>
				<version>3.0.0</version>
				<executions>
					<execution>
						<id>gantt.css</id>
						<phase>package</phase>
						<goals>
							<goal>java</goal>
						</goals>
						<configuration>
							<mainClass>com.sun.javafx.css.parser.Css2Bin
							</mainClass>
							<arguments>
								<argument>
									${project.basedir}/src/main/resources/com/flexganttfx/view/gantt.css
								</argument>
								<argument>
									${project.basedir}/target/classes/com/flexganttfx/view/gantt.bss
								</argument>
							</arguments>
						</configuration>
					</execution>
					<execution>
						<id>graphics.css</id>
						<phase>package</phase>
						<goals>
							<goal>java</goal>
						</goals>
						<configuration>
							<mainClass>com.sun.javafx.css.parser.Css2Bin
							</mainClass>
							<arguments>
								<argument>
									${project.basedir}/src/main/resources/com/flexganttfx/view/graphics/graphics.css
								</argument>
								<argument>
									${project.basedir}/target/classes/com/flexganttfx/view/graphics/graphics.bss
								</argument>
							</arguments>
						</configuration>
					</execution>
					<execution>
						<id>dateline.css</id>
						<phase>package</phase>
						<goals>
							<goal>java</goal>
						</goals>
						<configuration>
							<mainClass>com.sun.javafx.css.parser.Css2Bin
							</mainClass>
							<arguments>
								<argument>
									${project.basedir}/src/main/resources/com/flexganttfx/view/timeline/dateline.css
								</argument>
								<argument>
									${project.basedir}/target/classes/com/flexganttfx/view/timeline/dateline.bss
								</argument>
							</arguments>
						</configuration>
					</execution>
					<execution>
						<id>eventline.css</id>
						<phase>package</phase>
						<goals>
							<goal>java</goal>
						</goals>
						<configuration>
							<mainClass>com.sun.javafx.css.parser.Css2Bin
							</mainClass>
							<arguments>
								<argument>
									${project.basedir}/src/main/resources/com/flexganttfx/view/timeline/eventline.css
								</argument>
								<argument>
									${project.basedir}/target/classes/com/flexganttfx/view/timeline/eventline.bss
								</argument>
							</arguments>
						</configuration>
					</execution>
					<execution>
						<id>timeline.css</id>
						<phase>package</phase>
						<goals>
							<goal>java</goal>
						</goals>
						<configuration>
							<mainClass>com.sun.javafx.css.parser.Css2Bin
							</mainClass>
							<arguments>
								<argument>
									${project.basedir}/src/main/resources/com/flexganttfx/view/timeline/timeline.css
								</argument>
								<argument>
									${project.basedir}/target/classes/com/flexganttfx/view/timeline/timeline.bss
								</argument>
							</arguments>
						</configuration>
					</execution>
				</executions>
			</plugin>

		</plugins>
	</build>
</project>