/**
 * Copyright (C) 2014 - 2020 DLSC Software & Consulting GmbH (dlsc.com)
 *
 * This file is part of FlexGanttFX.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.04 at 05:49:11 PM CEST
//

package com.flexganttfx.emirates.model;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the com.dlsc.emirates.generated.flights
 * package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 *
 */
@XmlRegistry
public class ObjectFactory {

	private final static QName _AIRLINEDESIG_QNAME = new QName("",
			"AIRLINEDESIG");
	private final static QName _LEGSEQNO_QNAME = new QName("", "LEGSEQNO");
	private final static QName _INITORGDATE365_QNAME = new QName("",
			"INITORGDATE_365");
	private final static QName _IATAACFTTYPE_QNAME = new QName("",
			"IATAACFTTYPE");
	private final static QName _LOCALSTANDARDDEPTIME_QNAME = new QName("",
			"LOCALSTANDARDDEPTIME");
	private final static QName _FOLWORGDATE_QNAME = new QName("", "FOLWORGDATE");
	private final static QName _ACTYPE_QNAME = new QName("", "ACTYPE");
	private final static QName _AIRLINECODE_QNAME = new QName("", "AIRLINECODE");
	private final static QName _LTORIGINDATE_QNAME = new QName("",
			"LT_ORIGINDATE");
	private final static QName _FOLWFLIGHTNO_QNAME = new QName("",
			"FOLWFLIGHTNO");
	private final static QName _PRBD_QNAME = new QName("", "PRBD");
	private final static QName _FOLWFLTOPSUFFIX_QNAME = new QName("",
			"FOLWFLTOPSUFFIX");
	private final static QName _ONWARDROTATIONLAYOVER_QNAME = new QName("",
			"ONWARDROTATIONLAYOVER");
	private final static QName _PRBM_QNAME = new QName("", "PRBM");
	private final static QName _TRAFFICRES_QNAME = new QName("", "TRAFFICRES");
	private final static QName _MAINACSEQ_QNAME = new QName("", "MAINACSEQ");
	private final static QName _ACTIVITYID_QNAME = new QName("", "ACTIVITYID");
	private final static QName _ROUTEID_QNAME = new QName("", "ROUTEID");
	private final static QName _SERVICETYPE_QNAME = new QName("", "SERVICETYPE");
	private final static QName _UTCLTDEPVAR_QNAME = new QName("", "UTCLTDEPVAR");
	private final static QName _OLDLOCALACTYPE_QNAME = new QName("",
			"OLDLOCALACTYPE");
	private final static QName _FLIGHTDATE_QNAME = new QName("", "FLIGHTDATE");
	private final static QName _ISLOCKED_QNAME = new QName("", "ISLOCKED");
	private final static QName _DEPDATETIME_QNAME = new QName("", "DEPDATETIME");
	private final static QName _LOCALACFTTYPE_QNAME = new QName("",
			"LOCALACFTTYPE");
	private final static QName _REGID_QNAME = new QName("", "REGID");
	private final static QName _INITFLIGHTNO_QNAME = new QName("",
			"INITFLIGHTNO");
	private final static QName _OPSUFFIX_QNAME = new QName("", "OPSUFFIX");
	private final static QName _PREVORGDATE_QNAME = new QName("", "PREVORGDATE");
	private final static QName _IMPLMENTEDREGID_QNAME = new QName("",
			"IMPLMENTEDREGID");
	private final static QName _SCNCREATEDBY_QNAME = new QName("",
			"SCNCREATEDBY");
	private final static QName _UTCLTARRVAR_QNAME = new QName("", "UTCLTARRVAR");
	private final static QName _FLIGHTNO_QNAME = new QName("", "FLIGHTNO");
	private final static QName _ACTIVESCENARIO_QNAME = new QName("",
			"ACTIVESCENARIO");
	private final static QName _FLIGHTID_QNAME = new QName("", "FLIGHTID");
	private final static QName _REMARKS_QNAME = new QName("", "REMARKS");
	private final static QName _EXISTREQID_QNAME = new QName("", "EXISTREQID");
	private final static QName _ORIGINDATE_QNAME = new QName("", "ORIGINDATE");
	private final static QName _PREVFLTOPSUFFIX_QNAME = new QName("",
			"PREVFLTOPSUFFIX");
	private final static QName _FLTTYPE_QNAME = new QName("", "FLTTYPE");
	private final static QName _DEPARTURESTATION_QNAME = new QName("",
			"DEPARTURESTATION");
	private final static QName _STANDARDARRIVALTIME_QNAME = new QName("",
			"STANDARDARRIVALTIME");
	private final static QName _PREVFLIGHTNO_QNAME = new QName("",
			"PREVFLIGHTNO");
	private final static QName _SUBACSEQ_QNAME = new QName("", "SUBACSEQ");
	private final static QName _LTINITORGDATE_QNAME = new QName("",
			"LT_INITORGDATE");
	private final static QName _ACFTCONFIG_QNAME = new QName("", "ACFTCONFIG");
	private final static QName _LOCKEDON_QNAME = new QName("", "LOCKEDON");
	private final static QName _SESSIONID_QNAME = new QName("", "SESSIONID");
	private final static QName _SCNCREATEDON_QNAME = new QName("",
			"SCNCREATEDON");
	private final static QName _ARRIVALSTATION_QNAME = new QName("",
			"ARRIVALSTATION");
	private final static QName _Resource_QNAME = new QName("", "Resource");
	private final static QName _STANDARDDEPTIME_QNAME = new QName("",
			"STANDARDDEPTIME");
	private final static QName _LOCKTYPE_QNAME = new QName("", "LOCKTYPE");
	private final static QName _ARRIVALDATE_QNAME = new QName("", "ARRIVALDATE");
	private final static QName _LOCALFLIGHTDATE_QNAME = new QName("",
			"LOCALFLIGHTDATE");
	private final static QName _EXISTSCNID_QNAME = new QName("", "EXISTSCNID");
	private final static QName _LOCALSTANDARDARRIVALTIME_QNAME = new QName("",
			"LOCALSTANDARDARRIVALTIME");
	private final static QName _LOCALARRIVALDATE_QNAME = new QName("",
			"LOCALARRIVALDATE");
	private final static QName _ONWARDFLIGHTNO_QNAME = new QName("",
			"ONWARDFLIGHTNO");
	private final static QName _LOCKEDBY_QNAME = new QName("", "LOCKEDBY");
	private final static QName _SWAPPSUGGTYPE_QNAME = new QName("",
			"SWAPP_SUGG_TYPE");
	private final static QName _ROTATIONSEQ_QNAME = new QName("", "ROTATIONSEQ");
	private final static QName _CSRFLIGHTTYPE_QNAME = new QName("",
			"CSRFLIGHTTYPE");
	private final static QName _ONWARDOPSUFFIX_QNAME = new QName("",
			"ONWARDOPSUFFIX");

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: com.dlsc.emirates.generated.flights
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link ROW }
	 * 
	 */
	public ROW createROW() {
		return new ROW();
	}

	/**
	 * Create an instance of {@link ROWDATA }
	 * 
	 */
	public ROWDATA createROWDATA() {
		return new ROWDATA();
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "AIRLINEDESIG")
	public JAXBElement<String> createAIRLINEDESIG(String value) {
		return new JAXBElement<String>(_AIRLINEDESIG_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LEGSEQNO")
	public JAXBElement<Short> createLEGSEQNO(Short value) {
		return new JAXBElement<Short>(_LEGSEQNO_QNAME, Short.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "INITORGDATE_365")
	public JAXBElement<String> createINITORGDATE365(String value) {
		return new JAXBElement<String>(_INITORGDATE365_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IATAACFTTYPE")
	public JAXBElement<String> createIATAACFTTYPE(String value) {
		return new JAXBElement<String>(_IATAACFTTYPE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LOCALSTANDARDDEPTIME")
	public JAXBElement<Short> createLOCALSTANDARDDEPTIME(Short value) {
		return new JAXBElement<Short>(_LOCALSTANDARDDEPTIME_QNAME, Short.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "FOLWORGDATE")
	public JAXBElement<String> createFOLWORGDATE(String value) {
		return new JAXBElement<String>(_FOLWORGDATE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ACTYPE")
	public JAXBElement<String> createACTYPE(String value) {
		return new JAXBElement<String>(_ACTYPE_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "AIRLINECODE")
	public JAXBElement<String> createAIRLINECODE(String value) {
		return new JAXBElement<String>(_AIRLINECODE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LT_ORIGINDATE")
	public JAXBElement<String> createLTORIGINDATE(String value) {
		return new JAXBElement<String>(_LTORIGINDATE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "FOLWFLIGHTNO")
	public JAXBElement<Short> createFOLWFLIGHTNO(Short value) {
		return new JAXBElement<Short>(_FOLWFLIGHTNO_QNAME, Short.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "PRBD")
	public JAXBElement<String> createPRBD(String value) {
		return new JAXBElement<String>(_PRBD_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "FOLWFLTOPSUFFIX")
	public JAXBElement<String> createFOLWFLTOPSUFFIX(String value) {
		return new JAXBElement<String>(_FOLWFLTOPSUFFIX_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ONWARDROTATIONLAYOVER")
	public JAXBElement<String> createONWARDROTATIONLAYOVER(String value) {
		return new JAXBElement<String>(_ONWARDROTATIONLAYOVER_QNAME,
				String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "PRBM")
	public JAXBElement<String> createPRBM(String value) {
		return new JAXBElement<String>(_PRBM_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "TRAFFICRES")
	public JAXBElement<String> createTRAFFICRES(String value) {
		return new JAXBElement<String>(_TRAFFICRES_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "MAINACSEQ")
	public JAXBElement<String> createMAINACSEQ(String value) {
		return new JAXBElement<String>(_MAINACSEQ_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ACTIVITYID")
	public JAXBElement<String> createACTIVITYID(String value) {
		return new JAXBElement<String>(_ACTIVITYID_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ROUTEID")
	public JAXBElement<String> createROUTEID(String value) {
		return new JAXBElement<String>(_ROUTEID_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "SERVICETYPE")
	public JAXBElement<String> createSERVICETYPE(String value) {
		return new JAXBElement<String>(_SERVICETYPE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "UTCLTDEPVAR")
	public JAXBElement<Short> createUTCLTDEPVAR(Short value) {
		return new JAXBElement<Short>(_UTCLTDEPVAR_QNAME, Short.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "OLDLOCALACTYPE")
	public JAXBElement<String> createOLDLOCALACTYPE(String value) {
		return new JAXBElement<String>(_OLDLOCALACTYPE_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "FLIGHTDATE")
	public JAXBElement<String> createFLIGHTDATE(String value) {
		return new JAXBElement<String>(_FLIGHTDATE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ISLOCKED")
	public JAXBElement<String> createISLOCKED(String value) {
		return new JAXBElement<String>(_ISLOCKED_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "DEPDATETIME")
	public JAXBElement<String> createDEPDATETIME(String value) {
		return new JAXBElement<String>(_DEPDATETIME_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LOCALACFTTYPE")
	public JAXBElement<String> createLOCALACFTTYPE(String value) {
		return new JAXBElement<String>(_LOCALACFTTYPE_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "REGID")
	public JAXBElement<String> createREGID(String value) {
		return new JAXBElement<String>(_REGID_QNAME, String.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "INITFLIGHTNO")
	public JAXBElement<String> createINITFLIGHTNO(String value) {
		return new JAXBElement<String>(_INITFLIGHTNO_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "OPSUFFIX")
	public JAXBElement<String> createOPSUFFIX(String value) {
		return new JAXBElement<String>(_OPSUFFIX_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "PREVORGDATE")
	public JAXBElement<String> createPREVORGDATE(String value) {
		return new JAXBElement<String>(_PREVORGDATE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "IMPLMENTEDREGID")
	public JAXBElement<String> createIMPLMENTEDREGID(String value) {
		return new JAXBElement<String>(_IMPLMENTEDREGID_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "SCNCREATEDBY")
	public JAXBElement<String> createSCNCREATEDBY(String value) {
		return new JAXBElement<String>(_SCNCREATEDBY_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "UTCLTARRVAR")
	public JAXBElement<Short> createUTCLTARRVAR(Short value) {
		return new JAXBElement<Short>(_UTCLTARRVAR_QNAME, Short.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "FLIGHTNO")
	public JAXBElement<String> createFLIGHTNO(String value) {
		return new JAXBElement<String>(_FLIGHTNO_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ACTIVESCENARIO")
	public JAXBElement<String> createACTIVESCENARIO(String value) {
		return new JAXBElement<String>(_ACTIVESCENARIO_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "FLIGHTID")
	public JAXBElement<String> createFLIGHTID(String value) {
		return new JAXBElement<String>(_FLIGHTID_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "REMARKS")
	public JAXBElement<String> createREMARKS(String value) {
		return new JAXBElement<String>(_REMARKS_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "EXISTREQID")
	public JAXBElement<String> createEXISTREQID(String value) {
		return new JAXBElement<String>(_EXISTREQID_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ORIGINDATE")
	public JAXBElement<String> createORIGINDATE(String value) {
		return new JAXBElement<String>(_ORIGINDATE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "PREVFLTOPSUFFIX")
	public JAXBElement<String> createPREVFLTOPSUFFIX(String value) {
		return new JAXBElement<String>(_PREVFLTOPSUFFIX_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "FLTTYPE")
	public JAXBElement<String> createFLTTYPE(String value) {
		return new JAXBElement<String>(_FLTTYPE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "DEPARTURESTATION")
	public JAXBElement<String> createDEPARTURESTATION(String value) {
		return new JAXBElement<String>(_DEPARTURESTATION_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "STANDARDARRIVALTIME")
	public JAXBElement<Short> createSTANDARDARRIVALTIME(Short value) {
		return new JAXBElement<Short>(_STANDARDARRIVALTIME_QNAME, Short.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "PREVFLIGHTNO")
	public JAXBElement<Short> createPREVFLIGHTNO(Short value) {
		return new JAXBElement<Short>(_PREVFLIGHTNO_QNAME, Short.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "SUBACSEQ")
	public JAXBElement<Short> createSUBACSEQ(Short value) {
		return new JAXBElement<Short>(_SUBACSEQ_QNAME, Short.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LT_INITORGDATE")
	public JAXBElement<String> createLTINITORGDATE(String value) {
		return new JAXBElement<String>(_LTINITORGDATE_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ACFTCONFIG")
	public JAXBElement<String> createACFTCONFIG(String value) {
		return new JAXBElement<String>(_ACFTCONFIG_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LOCKEDON")
	public JAXBElement<String> createLOCKEDON(String value) {
		return new JAXBElement<String>(_LOCKEDON_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "SESSIONID")
	public JAXBElement<String> createSESSIONID(String value) {
		return new JAXBElement<String>(_SESSIONID_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "SCNCREATEDON")
	public JAXBElement<String> createSCNCREATEDON(String value) {
		return new JAXBElement<String>(_SCNCREATEDON_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ARRIVALSTATION")
	public JAXBElement<String> createARRIVALSTATION(String value) {
		return new JAXBElement<String>(_ARRIVALSTATION_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "Resource")
	public JAXBElement<String> createResource(String value) {
		return new JAXBElement<String>(_Resource_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "STANDARDDEPTIME")
	public JAXBElement<Short> createSTANDARDDEPTIME(Short value) {
		return new JAXBElement<Short>(_STANDARDDEPTIME_QNAME, Short.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LOCKTYPE")
	public JAXBElement<String> createLOCKTYPE(String value) {
		return new JAXBElement<String>(_LOCKTYPE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ARRIVALDATE")
	public JAXBElement<String> createARRIVALDATE(String value) {
		return new JAXBElement<String>(_ARRIVALDATE_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LOCALFLIGHTDATE")
	public JAXBElement<String> createLOCALFLIGHTDATE(String value) {
		return new JAXBElement<String>(_LOCALFLIGHTDATE_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "EXISTSCNID")
	public JAXBElement<String> createEXISTSCNID(String value) {
		return new JAXBElement<String>(_EXISTSCNID_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LOCALSTANDARDARRIVALTIME")
	public JAXBElement<Short> createLOCALSTANDARDARRIVALTIME(Short value) {
		return new JAXBElement<Short>(_LOCALSTANDARDARRIVALTIME_QNAME,
				Short.class, null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LOCALARRIVALDATE")
	public JAXBElement<String> createLOCALARRIVALDATE(String value) {
		return new JAXBElement<String>(_LOCALARRIVALDATE_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link Short }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ONWARDFLIGHTNO")
	public JAXBElement<Short> createONWARDFLIGHTNO(Short value) {
		return new JAXBElement<Short>(_ONWARDFLIGHTNO_QNAME, Short.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "LOCKEDBY")
	public JAXBElement<String> createLOCKEDBY(String value) {
		return new JAXBElement<String>(_LOCKEDBY_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "SWAPP_SUGG_TYPE")
	public JAXBElement<String> createSWAPPSUGGTYPE(String value) {
		return new JAXBElement<String>(_SWAPPSUGGTYPE_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ROTATIONSEQ")
	public JAXBElement<String> createROTATIONSEQ(String value) {
		return new JAXBElement<String>(_ROTATIONSEQ_QNAME, String.class, null,
				value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "CSRFLIGHTTYPE")
	public JAXBElement<String> createCSRFLIGHTTYPE(String value) {
		return new JAXBElement<String>(_CSRFLIGHTTYPE_QNAME, String.class,
				null, value);
	}

	/**
	 * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
	 * 
	 */
	@XmlElementDecl(namespace = "", name = "ONWARDOPSUFFIX")
	public JAXBElement<String> createONWARDOPSUFFIX(String value) {
		return new JAXBElement<String>(_ONWARDOPSUFFIX_QNAME, String.class,
				null, value);
	}

}
