/**
 * Copyright (C) 2014 - 2020 DLSC Software & Consulting GmbH (dlsc.com)
 *
 * This file is part of FlexGanttFX.
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2013.04.04 at 05:49:11 PM CEST
//

package com.flexganttfx.emirates.model;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 *
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 *
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}FLIGHTID"/>
 *         &lt;element ref="{}ROUTEID"/>
 *         &lt;element ref="{}ACTIVITYID"/>
 *         &lt;element ref="{}Resource"/>
 *         &lt;element ref="{}ACFTCONFIG"/>
 *         &lt;element ref="{}ACTYPE"/>
 *         &lt;element ref="{}AIRLINEDESIG"/>
 *         &lt;element ref="{}ARRIVALDATE"/>
 *         &lt;element ref="{}ARRIVALSTATION"/>
 *         &lt;element ref="{}DEPARTURESTATION"/>
 *         &lt;element ref="{}DEPDATETIME"/>
 *         &lt;element ref="{}CSRFLIGHTTYPE"/>
 *         &lt;element ref="{}FLIGHTDATE"/>
 *         &lt;element ref="{}FLIGHTNO"/>
 *         &lt;element ref="{}FOLWFLIGHTNO"/>
 *         &lt;element ref="{}FOLWFLTOPSUFFIX"/>
 *         &lt;element ref="{}FOLWORGDATE"/>
 *         &lt;element ref="{}INITFLIGHTNO"/>
 *         &lt;element ref="{}INITORGDATE_365"/>
 *         &lt;element ref="{}LEGSEQNO"/>
 *         &lt;element ref="{}LOCALACFTTYPE"/>
 *         &lt;element ref="{}LOCALARRIVALDATE"/>
 *         &lt;element ref="{}LOCALSTANDARDARRIVALTIME"/>
 *         &lt;element ref="{}LOCALSTANDARDDEPTIME"/>
 *         &lt;element ref="{}LOCALFLIGHTDATE"/>
 *         &lt;element ref="{}LT_INITORGDATE"/>
 *         &lt;element ref="{}LT_ORIGINDATE"/>
 *         &lt;element ref="{}MAINACSEQ"/>
 *         &lt;element ref="{}AIRLINECODE"/>
 *         &lt;element ref="{}ONWARDFLIGHTNO"/>
 *         &lt;element ref="{}ONWARDOPSUFFIX"/>
 *         &lt;element ref="{}ONWARDROTATIONLAYOVER"/>
 *         &lt;element ref="{}OPSUFFIX"/>
 *         &lt;element ref="{}ORIGINDATE"/>
 *         &lt;element ref="{}PRBD"/>
 *         &lt;element ref="{}PRBM"/>
 *         &lt;element ref="{}PREVFLIGHTNO"/>
 *         &lt;element ref="{}PREVFLTOPSUFFIX"/>
 *         &lt;element ref="{}PREVORGDATE"/>
 *         &lt;element ref="{}ROTATIONSEQ"/>
 *         &lt;element ref="{}SERVICETYPE"/>
 *         &lt;element ref="{}STANDARDARRIVALTIME"/>
 *         &lt;element ref="{}STANDARDDEPTIME"/>
 *         &lt;element ref="{}TRAFFICRES"/>
 *         &lt;element ref="{}UTCLTARRVAR"/>
 *         &lt;element ref="{}UTCLTDEPVAR"/>
 *         &lt;element ref="{}REGID"/>
 *         &lt;element ref="{}OLDLOCALACTYPE"/>
 *         &lt;element ref="{}IATAACFTTYPE"/>
 *         &lt;element ref="{}REMARKS"/>
 *         &lt;element ref="{}EXISTREQID"/>
 *         &lt;element ref="{}EXISTSCNID"/>
 *         &lt;element ref="{}FLTTYPE"/>
 *         &lt;element ref="{}SCNCREATEDBY"/>
 *         &lt;element ref="{}SCNCREATEDON"/>
 *         &lt;element ref="{}IMPLMENTEDREGID"/>
 *         &lt;element ref="{}ACTIVESCENARIO"/>
 *         &lt;element ref="{}ISLOCKED"/>
 *         &lt;element ref="{}LOCKEDBY"/>
 *         &lt;element ref="{}LOCKEDON"/>
 *         &lt;element ref="{}LOCKTYPE"/>
 *         &lt;element ref="{}SESSIONID"/>
 *         &lt;element ref="{}SWAPP_SUGG_TYPE"/>
 *         &lt;element ref="{}SUBACSEQ"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 *
 *
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "flightid", "routeid", "activityid",
		"resource", "acftconfig", "actype", "airlinedesig", "arrivaldate",
		"arrivalstation", "departurestation", "depdatetime", "csrflighttype",
		"flightdate", "flightno", "folwflightno", "folwfltopsuffix",
		"folworgdate", "initflightno", "initorgdate365", "legseqno",
		"localacfttype", "localarrivaldate", "localstandardarrivaltime",
		"localstandarddeptime", "localflightdate", "ltinitorgdate",
		"ltorigindate", "mainacseq", "airlinecode", "onwardflightno",
		"onwardopsuffix", "onwardrotationlayover", "opsuffix", "origindate",
		"prbd", "prbm", "prevflightno", "prevfltopsuffix", "prevorgdate",
		"rotationseq", "servicetype", "standardarrivaltime", "standarddeptime",
		"trafficres", "utcltarrvar", "utcltdepvar", "regid", "oldlocalactype",
		"iataacfttype", "remarks", "existreqid", "existscnid", "flttype",
		"scncreatedby", "scncreatedon", "implmentedregid", "activescenario",
		"islocked", "lockedby", "lockedon", "locktype", "sessionid",
		"swappsuggtype", "subacseq" })
@XmlRootElement(name = "ROW")
public class ROW implements Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4399180764312010789L;
	@XmlElement(name = "FLIGHTID", required = true)
	protected String flightid;
	@XmlElement(name = "ROUTEID", required = true)
	protected String routeid;
	@XmlElement(name = "ACTIVITYID", required = true)
	protected String activityid;
	@XmlElement(name = "Resource", required = true)
	protected String resource;
	@XmlElement(name = "ACFTCONFIG", required = true)
	protected String acftconfig;
	@XmlElement(name = "ACTYPE", required = true)
	protected String actype;
	@XmlElement(name = "AIRLINEDESIG", required = true)
	protected String airlinedesig;
	@XmlElement(name = "ARRIVALDATE", required = true)
	protected String arrivaldate;
	@XmlElement(name = "ARRIVALSTATION", required = true)
	protected String arrivalstation;
	@XmlElement(name = "DEPARTURESTATION", required = true)
	protected String departurestation;
	@XmlElement(name = "DEPDATETIME", required = true)
	protected String depdatetime;
	@XmlElement(name = "CSRFLIGHTTYPE", required = true)
	protected String csrflighttype;
	@XmlElement(name = "FLIGHTDATE", required = true)
	protected String flightdate;
	@XmlElement(name = "FLIGHTNO", required = true)
	protected String flightno;
	@XmlElement(name = "FOLWFLIGHTNO")
	protected short folwflightno;
	@XmlElement(name = "FOLWFLTOPSUFFIX", required = true)
	protected String folwfltopsuffix;
	@XmlElement(name = "FOLWORGDATE", required = true)
	protected String folworgdate;
	@XmlElement(name = "INITFLIGHTNO", required = true)
	protected String initflightno;
	@XmlElement(name = "INITORGDATE_365", required = true)
	protected String initorgdate365;
	@XmlElement(name = "LEGSEQNO")
	protected short legseqno;
	@XmlElement(name = "LOCALACFTTYPE", required = true)
	protected String localacfttype;
	@XmlElement(name = "LOCALARRIVALDATE", required = true)
	protected String localarrivaldate;
	@XmlElement(name = "LOCALSTANDARDARRIVALTIME")
	protected short localstandardarrivaltime;
	@XmlElement(name = "LOCALSTANDARDDEPTIME")
	protected short localstandarddeptime;
	@XmlElement(name = "LOCALFLIGHTDATE", required = true)
	protected String localflightdate;
	@XmlElement(name = "LT_INITORGDATE", required = true)
	protected String ltinitorgdate;
	@XmlElement(name = "LT_ORIGINDATE", required = true)
	protected String ltorigindate;
	@XmlElement(name = "MAINACSEQ", required = true)
	protected String mainacseq;
	@XmlElement(name = "AIRLINECODE", required = true)
	protected String airlinecode;
	@XmlElement(name = "ONWARDFLIGHTNO")
	protected short onwardflightno;
	@XmlElement(name = "ONWARDOPSUFFIX", required = true)
	protected String onwardopsuffix;
	@XmlElement(name = "ONWARDROTATIONLAYOVER", required = true)
	protected String onwardrotationlayover;
	@XmlElement(name = "OPSUFFIX", required = true)
	protected String opsuffix;
	@XmlElement(name = "ORIGINDATE", required = true)
	protected String origindate;
	@XmlElement(name = "PRBD", required = true)
	protected String prbd;
	@XmlElement(name = "PRBM", required = true)
	protected String prbm;
	@XmlElement(name = "PREVFLIGHTNO")
	protected short prevflightno;
	@XmlElement(name = "PREVFLTOPSUFFIX", required = true)
	protected String prevfltopsuffix;
	@XmlElement(name = "PREVORGDATE", required = true)
	protected String prevorgdate;
	@XmlElement(name = "ROTATIONSEQ", required = true)
	protected String rotationseq;
	@XmlElement(name = "SERVICETYPE", required = true)
	protected String servicetype;
	@XmlElement(name = "STANDARDARRIVALTIME")
	protected short standardarrivaltime;
	@XmlElement(name = "STANDARDDEPTIME")
	protected short standarddeptime;
	@XmlElement(name = "TRAFFICRES", required = true)
	protected String trafficres;
	@XmlElement(name = "UTCLTARRVAR")
	protected short utcltarrvar;
	@XmlElement(name = "UTCLTDEPVAR")
	protected short utcltdepvar;
	@XmlElement(name = "REGID", required = true)
	protected String regid;
	@XmlElement(name = "OLDLOCALACTYPE", required = true)
	protected String oldlocalactype;
	@XmlElement(name = "IATAACFTTYPE", required = true)
	protected String iataacfttype;
	@XmlElement(name = "REMARKS", required = true)
	protected String remarks;
	@XmlElement(name = "EXISTREQID", required = true)
	protected String existreqid;
	@XmlElement(name = "EXISTSCNID", required = true)
	protected String existscnid;
	@XmlElement(name = "FLTTYPE", required = true)
	protected String flttype;
	@XmlElement(name = "SCNCREATEDBY", required = true)
	protected String scncreatedby;
	@XmlElement(name = "SCNCREATEDON", required = true)
	protected String scncreatedon;
	@XmlElement(name = "IMPLMENTEDREGID", required = true)
	protected String implmentedregid;
	@XmlElement(name = "ACTIVESCENARIO", required = true)
	protected String activescenario;
	@XmlElement(name = "ISLOCKED", required = true)
	protected String islocked;
	@XmlElement(name = "LOCKEDBY", required = true)
	protected String lockedby;
	@XmlElement(name = "LOCKEDON", required = true)
	protected String lockedon;
	@XmlElement(name = "LOCKTYPE", required = true)
	protected String locktype;
	@XmlElement(name = "SESSIONID", required = true)
	protected String sessionid;
	@XmlElement(name = "SWAPP_SUGG_TYPE", required = true)
	protected String swappsuggtype;
	@XmlElement(name = "SUBACSEQ")
	protected short subacseq;

	/**
	 * Gets the value of the flightid property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getFLIGHTID() {
		return flightid;
	}

	/**
	 * Sets the value of the flightid property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setFLIGHTID(String value) {
		this.flightid = value;
	}

	/**
	 * Gets the value of the routeid property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getROUTEID() {
		return routeid;
	}

	/**
	 * Sets the value of the routeid property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setROUTEID(String value) {
		this.routeid = value;
	}

	/**
	 * Gets the value of the activityid property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getACTIVITYID() {
		return activityid;
	}

	/**
	 * Sets the value of the activityid property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setACTIVITYID(String value) {
		this.activityid = value;
	}

	/**
	 * Gets the value of the resource property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getResource() {
		return resource;
	}

	/**
	 * Sets the value of the resource property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setResource(String value) {
		this.resource = value;
	}

	/**
	 * Gets the value of the acftconfig property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getACFTCONFIG() {
		return acftconfig;
	}

	/**
	 * Sets the value of the acftconfig property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setACFTCONFIG(String value) {
		this.acftconfig = value;
	}

	/**
	 * Gets the value of the actype property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getACTYPE() {
		return actype;
	}

	/**
	 * Sets the value of the actype property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setACTYPE(String value) {
		this.actype = value;
	}

	/**
	 * Gets the value of the airlinedesig property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getAIRLINEDESIG() {
		return airlinedesig;
	}

	/**
	 * Sets the value of the airlinedesig property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setAIRLINEDESIG(String value) {
		this.airlinedesig = value;
	}

	/**
	 * Gets the value of the arrivaldate property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getARRIVALDATE() {
		return arrivaldate;
	}

	/**
	 * Sets the value of the arrivaldate property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setARRIVALDATE(String value) {
		this.arrivaldate = value;
	}

	/**
	 * Gets the value of the arrivalstation property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getARRIVALSTATION() {
		return arrivalstation;
	}

	/**
	 * Sets the value of the arrivalstation property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setARRIVALSTATION(String value) {
		this.arrivalstation = value;
	}

	/**
	 * Gets the value of the departurestation property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDEPARTURESTATION() {
		return departurestation;
	}

	/**
	 * Sets the value of the departurestation property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setDEPARTURESTATION(String value) {
		this.departurestation = value;
	}

	/**
	 * Gets the value of the depdatetime property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getDEPDATETIME() {
		return depdatetime;
	}

	/**
	 * Sets the value of the depdatetime property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setDEPDATETIME(String value) {
		this.depdatetime = value;
	}

	/**
	 * Gets the value of the csrflighttype property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getCSRFLIGHTTYPE() {
		return csrflighttype;
	}

	/**
	 * Sets the value of the csrflighttype property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setCSRFLIGHTTYPE(String value) {
		this.csrflighttype = value;
	}

	/**
	 * Gets the value of the flightdate property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getFLIGHTDATE() {
		return flightdate;
	}

	/**
	 * Sets the value of the flightdate property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setFLIGHTDATE(String value) {
		this.flightdate = value;
	}

	/**
	 * Gets the value of the flightno property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getFLIGHTNO() {
		return flightno;
	}

	/**
	 * Sets the value of the flightno property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setFLIGHTNO(String value) {
		this.flightno = value;
	}

	/**
	 * Gets the value of the folwflightno property.
	 *
	 */
	public short getFOLWFLIGHTNO() {
		return folwflightno;
	}

	/**
	 * Sets the value of the folwflightno property.
	 *
	 */
	public void setFOLWFLIGHTNO(short value) {
		this.folwflightno = value;
	}

	/**
	 * Gets the value of the folwfltopsuffix property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getFOLWFLTOPSUFFIX() {
		return folwfltopsuffix;
	}

	/**
	 * Sets the value of the folwfltopsuffix property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setFOLWFLTOPSUFFIX(String value) {
		this.folwfltopsuffix = value;
	}

	/**
	 * Gets the value of the folworgdate property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getFOLWORGDATE() {
		return folworgdate;
	}

	/**
	 * Sets the value of the folworgdate property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setFOLWORGDATE(String value) {
		this.folworgdate = value;
	}

	/**
	 * Gets the value of the initflightno property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getINITFLIGHTNO() {
		return initflightno;
	}

	/**
	 * Sets the value of the initflightno property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setINITFLIGHTNO(String value) {
		this.initflightno = value;
	}

	/**
	 * Gets the value of the initorgdate365 property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getINITORGDATE365() {
		return initorgdate365;
	}

	/**
	 * Sets the value of the initorgdate365 property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setINITORGDATE365(String value) {
		this.initorgdate365 = value;
	}

	/**
	 * Gets the value of the legseqno property.
	 *
	 */
	public short getLEGSEQNO() {
		return legseqno;
	}

	/**
	 * Sets the value of the legseqno property.
	 *
	 */
	public void setLEGSEQNO(short value) {
		this.legseqno = value;
	}

	/**
	 * Gets the value of the localacfttype property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLOCALACFTTYPE() {
		return localacfttype;
	}

	/**
	 * Sets the value of the localacfttype property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLOCALACFTTYPE(String value) {
		this.localacfttype = value;
	}

	/**
	 * Gets the value of the localarrivaldate property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLOCALARRIVALDATE() {
		return localarrivaldate;
	}

	/**
	 * Sets the value of the localarrivaldate property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLOCALARRIVALDATE(String value) {
		this.localarrivaldate = value;
	}

	/**
	 * Gets the value of the localstandardarrivaltime property.
	 *
	 */
	public short getLOCALSTANDARDARRIVALTIME() {
		return localstandardarrivaltime;
	}

	/**
	 * Sets the value of the localstandardarrivaltime property.
	 *
	 */
	public void setLOCALSTANDARDARRIVALTIME(short value) {
		this.localstandardarrivaltime = value;
	}

	/**
	 * Gets the value of the localstandarddeptime property.
	 *
	 */
	public short getLOCALSTANDARDDEPTIME() {
		return localstandarddeptime;
	}

	/**
	 * Sets the value of the localstandarddeptime property.
	 *
	 */
	public void setLOCALSTANDARDDEPTIME(short value) {
		this.localstandarddeptime = value;
	}

	/**
	 * Gets the value of the localflightdate property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLOCALFLIGHTDATE() {
		return localflightdate;
	}

	/**
	 * Sets the value of the localflightdate property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLOCALFLIGHTDATE(String value) {
		this.localflightdate = value;
	}

	/**
	 * Gets the value of the ltinitorgdate property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLTINITORGDATE() {
		return ltinitorgdate;
	}

	/**
	 * Sets the value of the ltinitorgdate property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLTINITORGDATE(String value) {
		this.ltinitorgdate = value;
	}

	/**
	 * Gets the value of the ltorigindate property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLTORIGINDATE() {
		return ltorigindate;
	}

	/**
	 * Sets the value of the ltorigindate property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLTORIGINDATE(String value) {
		this.ltorigindate = value;
	}

	/**
	 * Gets the value of the mainacseq property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getMAINACSEQ() {
		return mainacseq;
	}

	/**
	 * Sets the value of the mainacseq property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setMAINACSEQ(String value) {
		this.mainacseq = value;
	}

	/**
	 * Gets the value of the airlinecode property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getAIRLINECODE() {
		return airlinecode;
	}

	/**
	 * Sets the value of the airlinecode property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setAIRLINECODE(String value) {
		this.airlinecode = value;
	}

	/**
	 * Gets the value of the onwardflightno property.
	 *
	 */
	public short getONWARDFLIGHTNO() {
		return onwardflightno;
	}

	/**
	 * Sets the value of the onwardflightno property.
	 *
	 */
	public void setONWARDFLIGHTNO(short value) {
		this.onwardflightno = value;
	}

	/**
	 * Gets the value of the onwardopsuffix property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getONWARDOPSUFFIX() {
		return onwardopsuffix;
	}

	/**
	 * Sets the value of the onwardopsuffix property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setONWARDOPSUFFIX(String value) {
		this.onwardopsuffix = value;
	}

	/**
	 * Gets the value of the onwardrotationlayover property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getONWARDROTATIONLAYOVER() {
		return onwardrotationlayover;
	}

	/**
	 * Sets the value of the onwardrotationlayover property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setONWARDROTATIONLAYOVER(String value) {
		this.onwardrotationlayover = value;
	}

	/**
	 * Gets the value of the opsuffix property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getOPSUFFIX() {
		return opsuffix;
	}

	/**
	 * Sets the value of the opsuffix property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setOPSUFFIX(String value) {
		this.opsuffix = value;
	}

	/**
	 * Gets the value of the origindate property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getORIGINDATE() {
		return origindate;
	}

	/**
	 * Sets the value of the origindate property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setORIGINDATE(String value) {
		this.origindate = value;
	}

	/**
	 * Gets the value of the prbd property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getPRBD() {
		return prbd;
	}

	/**
	 * Sets the value of the prbd property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setPRBD(String value) {
		this.prbd = value;
	}

	/**
	 * Gets the value of the prbm property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getPRBM() {
		return prbm;
	}

	/**
	 * Sets the value of the prbm property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setPRBM(String value) {
		this.prbm = value;
	}

	/**
	 * Gets the value of the prevflightno property.
	 *
	 */
	public short getPREVFLIGHTNO() {
		return prevflightno;
	}

	/**
	 * Sets the value of the prevflightno property.
	 *
	 */
	public void setPREVFLIGHTNO(short value) {
		this.prevflightno = value;
	}

	/**
	 * Gets the value of the prevfltopsuffix property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getPREVFLTOPSUFFIX() {
		return prevfltopsuffix;
	}

	/**
	 * Sets the value of the prevfltopsuffix property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setPREVFLTOPSUFFIX(String value) {
		this.prevfltopsuffix = value;
	}

	/**
	 * Gets the value of the prevorgdate property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getPREVORGDATE() {
		return prevorgdate;
	}

	/**
	 * Sets the value of the prevorgdate property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setPREVORGDATE(String value) {
		this.prevorgdate = value;
	}

	/**
	 * Gets the value of the rotationseq property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getROTATIONSEQ() {
		return rotationseq;
	}

	/**
	 * Sets the value of the rotationseq property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setROTATIONSEQ(String value) {
		this.rotationseq = value;
	}

	/**
	 * Gets the value of the servicetype property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSERVICETYPE() {
		return servicetype;
	}

	/**
	 * Sets the value of the servicetype property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setSERVICETYPE(String value) {
		this.servicetype = value;
	}

	/**
	 * Gets the value of the standardarrivaltime property.
	 *
	 */
	public short getSTANDARDARRIVALTIME() {
		return standardarrivaltime;
	}

	/**
	 * Sets the value of the standardarrivaltime property.
	 *
	 */
	public void setSTANDARDARRIVALTIME(short value) {
		this.standardarrivaltime = value;
	}

	/**
	 * Gets the value of the standarddeptime property.
	 *
	 */
	public short getSTANDARDDEPTIME() {
		return standarddeptime;
	}

	/**
	 * Sets the value of the standarddeptime property.
	 *
	 */
	public void setSTANDARDDEPTIME(short value) {
		this.standarddeptime = value;
	}

	/**
	 * Gets the value of the trafficres property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getTRAFFICRES() {
		return trafficres;
	}

	/**
	 * Sets the value of the trafficres property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setTRAFFICRES(String value) {
		this.trafficres = value;
	}

	/**
	 * Gets the value of the utcltarrvar property.
	 *
	 */
	public short getUTCLTARRVAR() {
		return utcltarrvar;
	}

	/**
	 * Sets the value of the utcltarrvar property.
	 *
	 */
	public void setUTCLTARRVAR(short value) {
		this.utcltarrvar = value;
	}

	/**
	 * Gets the value of the utcltdepvar property.
	 *
	 */
	public short getUTCLTDEPVAR() {
		return utcltdepvar;
	}

	/**
	 * Sets the value of the utcltdepvar property.
	 *
	 */
	public void setUTCLTDEPVAR(short value) {
		this.utcltdepvar = value;
	}

	/**
	 * Gets the value of the regid property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getREGID() {
		return regid;
	}

	/**
	 * Sets the value of the regid property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setREGID(String value) {
		this.regid = value;
	}

	/**
	 * Gets the value of the oldlocalactype property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getOLDLOCALACTYPE() {
		return oldlocalactype;
	}

	/**
	 * Sets the value of the oldlocalactype property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setOLDLOCALACTYPE(String value) {
		this.oldlocalactype = value;
	}

	/**
	 * Gets the value of the iataacfttype property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getIATAACFTTYPE() {
		return iataacfttype;
	}

	/**
	 * Sets the value of the iataacfttype property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setIATAACFTTYPE(String value) {
		this.iataacfttype = value;
	}

	/**
	 * Gets the value of the remarks property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getREMARKS() {
		return remarks;
	}

	/**
	 * Sets the value of the remarks property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setREMARKS(String value) {
		this.remarks = value;
	}

	/**
	 * Gets the value of the existreqid property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getEXISTREQID() {
		return existreqid;
	}

	/**
	 * Sets the value of the existreqid property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setEXISTREQID(String value) {
		this.existreqid = value;
	}

	/**
	 * Gets the value of the existscnid property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getEXISTSCNID() {
		return existscnid;
	}

	/**
	 * Sets the value of the existscnid property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setEXISTSCNID(String value) {
		this.existscnid = value;
	}

	/**
	 * Gets the value of the flttype property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getFLTTYPE() {
		return flttype;
	}

	/**
	 * Sets the value of the flttype property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setFLTTYPE(String value) {
		this.flttype = value;
	}

	/**
	 * Gets the value of the scncreatedby property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSCNCREATEDBY() {
		return scncreatedby;
	}

	/**
	 * Sets the value of the scncreatedby property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setSCNCREATEDBY(String value) {
		this.scncreatedby = value;
	}

	/**
	 * Gets the value of the scncreatedon property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSCNCREATEDON() {
		return scncreatedon;
	}

	/**
	 * Sets the value of the scncreatedon property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setSCNCREATEDON(String value) {
		this.scncreatedon = value;
	}

	/**
	 * Gets the value of the implmentedregid property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getIMPLMENTEDREGID() {
		return implmentedregid;
	}

	/**
	 * Sets the value of the implmentedregid property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setIMPLMENTEDREGID(String value) {
		this.implmentedregid = value;
	}

	/**
	 * Gets the value of the activescenario property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getACTIVESCENARIO() {
		return activescenario;
	}

	/**
	 * Sets the value of the activescenario property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setACTIVESCENARIO(String value) {
		this.activescenario = value;
	}

	/**
	 * Gets the value of the islocked property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getISLOCKED() {
		return islocked;
	}

	/**
	 * Sets the value of the islocked property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setISLOCKED(String value) {
		this.islocked = value;
	}

	/**
	 * Gets the value of the lockedby property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLOCKEDBY() {
		return lockedby;
	}

	/**
	 * Sets the value of the lockedby property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLOCKEDBY(String value) {
		this.lockedby = value;
	}

	/**
	 * Gets the value of the lockedon property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLOCKEDON() {
		return lockedon;
	}

	/**
	 * Sets the value of the lockedon property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLOCKEDON(String value) {
		this.lockedon = value;
	}

	/**
	 * Gets the value of the locktype property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getLOCKTYPE() {
		return locktype;
	}

	/**
	 * Sets the value of the locktype property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setLOCKTYPE(String value) {
		this.locktype = value;
	}

	/**
	 * Gets the value of the sessionid property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSESSIONID() {
		return sessionid;
	}

	/**
	 * Sets the value of the sessionid property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setSESSIONID(String value) {
		this.sessionid = value;
	}

	/**
	 * Gets the value of the swappsuggtype property.
	 *
	 * @return possible object is {@link String }
	 *
	 */
	public String getSWAPPSUGGTYPE() {
		return swappsuggtype;
	}

	/**
	 * Sets the value of the swappsuggtype property.
	 *
	 * @param value
	 *            allowed object is {@link String }
	 *
	 */
	public void setSWAPPSUGGTYPE(String value) {
		this.swappsuggtype = value;
	}

	/**
	 * Gets the value of the subacseq property.
	 *
	 */
	public short getSUBACSEQ() {
		return subacseq;
	}

	/**
	 * Sets the value of the subacseq property.
	 *
	 */
	public void setSUBACSEQ(short value) {
		this.subacseq = value;
	}

}
