<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<artifactId>extras</artifactId>
	<name>FlexGanttFXExtras</name>
	<description>Utility controls for the Gantt chart control.</description>
	<packaging>bundle</packaging>
	
	<parent>
		<groupId>com.flexganttfx</groupId>
		<artifactId>gantt</artifactId>
		<version>11.12.3-SNAPSHOT</version>
		<relativePath>../pom.xml</relativePath>
	</parent>

	<properties>
		<maven.javadoc.skip>false</maven.javadoc.skip>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.flexganttfx</groupId>
			<artifactId>view</artifactId>
			<version>${project.parent.version}</version>
		</dependency>

		<dependency>
			<groupId>org.kordamp.ikonli</groupId>
			<artifactId>ikonli-core</artifactId>
			<version>${ikonli.version}</version>
		</dependency>

		<dependency>
			<groupId>org.kordamp.ikonli</groupId>
			<artifactId>ikonli-materialdesign-pack</artifactId>
			<version>${ikonli.version}</version>
		</dependency>

		<dependency>
			<groupId>org.kordamp.ikonli</groupId>
			<artifactId>ikonli-javafx</artifactId>
			<version>${ikonli.version}</version>
		</dependency>
 
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.felix</groupId>
				<artifactId>maven-bundle-plugin</artifactId>
				<version>${apache.felix.version}</version>
				<extensions>true</extensions>
				<configuration>
					<instructions>
						<Export-Package>com.flexganttfx.extras.*,impl.com.flexganttfx.extras.skin.*</Export-Package>
					</instructions>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>