# To use this property file add the following command line argument:
#    -Djava.util.logging.config.file=${project_loc}/log.properties

# Specify the handlers to create in the root logger
# (all loggers are children of the root logger)
# The following creates two handlers
# handlers = java.util.logging.ConsoleHandler, java.util.logging.FileHandler
handlers = java.util.logging.ConsoleHandler

# Set the default logging level for the root logger
.level = OFF

# Set the default logging level for new ConsoleHandler instances
java.util.logging.ConsoleHandler.level = OFF

# Set the default logging level for new FileHandler instances
# java.util.logging.FileHandler.level = ALL

# Set the default formatter for new ConsoleHandler instances
java.util.logging.ConsoleHandler.formatter = com.flexganttfx.core.LoggingFormatter

# LOG DOMAINS
com.flexganttfx.performance.level = OFF
com.flexganttfx.config.level = OFF
com.flexganttfx.repository.level = OFF
com.flexganttfx.model.level = OFF
com.flexganttfx.editing.level = OFF
com.flexganttfx.navigation.level = OFF
com.flexganttfx.rendering.level = OFF
com.flexganttfx.events.level = OFF
com.flexganttfx.dnd.level = OFF
