- title: Consulting
  icon: /assets/images/service-icon2.png
  description: FlexGanttFX is complex, but supported by DLSC GmbH. We will help you get off the ground quickly.
  button_label: Visit Site
  url: https://www.dlsc.com

- title: Question Answer
  icon: /assets/images/service-icon.png
  description:  Some questions just pop up over and over again. Check them out in our FAQ collection.
  button_label: Read FAQ
  url: /pages/faq/
  
- title: Documentation
  icon: /assets/images/service-icon3.png
  description:  The extensive online developer manual covers all the important aspects of the framework.
  button_label: Read Docs
  url: /pages/explore-topics/
  