name: 'Release'
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Java
        uses: ./.github/actions/prepare-java

      - name: 'Version'
        id: vars
        shell: bash
        run: |
          version=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          echo ::set-output name=VERSION::$(echo "$version")

      - name: 'Cache Maven packages'
        uses: actions/cache@v5
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 'Build with Maven'
        run: mvn -B install --file pom.xml

      - name: 'Create Release'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: 'Upload Binaries'
        id: upload-zip-binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./FlexGanttFXAssembly/target/flexganttfx-${{ steps.version.outputs.VERSION }}-bin.zip
          asset_name: flexganttfx-${{ steps.version.outputs.VERSION }}-bin.zip
          asset_content_type: application/zip

      - name: 'Upload Source Code'
        id: upload-zip-source-code
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./FlexGanttFXAssembly/target/flexganttfx-${{ steps.version.outputs.VERSION }}-src.zip
          asset_name: flexganttfx-${{ steps.version.outputs.VERSION }}-src.zip
          asset_content_type: application/zip
